name: Daily News Build & Deploy

on:
  schedule:
    # 每天 UTC 00:00 = 台湾/中国早上 8 点
    - cron: "0 0 * * *"

  workflow_dispatch: # 允许手动触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # ⭐ 关键：抓取新闻
      - name: Fetch latest news
        run: npm run build-news

      - name: Build project
        run: npm run build

      # ⭐ 自动部署到 Vercel
      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
